[colors.bright]
black = "#545454"
blue = "#00ffff"
cyan = "#00ffff"
green = "#00ff00"
magenta = "#ff00ff"
red = "#ff0000"
white = "#ffffff"
yellow = "#ffff00"

[colors.normal]
black = "#232323"
blue = "#00ffff"
cyan = "#00ffff"
green = "#00ff00"
magenta = "#ff00ff"
red = "#ff0000"
white = "#ffffff"
yellow = "#ffff00"

[colors.primary]
background = "#000000"
foreground = "#ffffff"

[font]
size = 11.0

[font.bold]
family = "hack"
style = "Bold"

[font.bold_italic]
family = "monospace"
style = "Bold Italic"

[font.italic]
family = "hack"
style = "Italic"

[font.normal]
family = "hack"
style = "Regular"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[scrolling]
history = 50000

[window]
opacity = 0.9
